title: John Jun's Insight-capturing blog
description: > # this means to ignore newlines until "baseurl:"
  Welcome to John Jun's Insight-Capturing Blog, where thought-provoking ideas meet practical wisdom. Here, you'll find reflections, analyses, and fresh perspectives on topics that matter, curated to inspire growth and ignite meaningful conversations. Dive in and discover the insights that will fuel your journey!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnwjun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: John Jun # add your name
author-img: AvatarMaker.png # add your photo
about-author: I am a web developer focusing on front-end/back-end development in Marketing Solutions. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: JohnWJun # add your Github handle
social-linkedin: john-jun-35650a21b # add your Linkedin handle
social-email: john.jun@parksystems.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
